/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_fhr_jnidemo_complex_Employee */

#ifndef _Included_com_fhr_jnidemo_complex_Employee
#define _Included_com_fhr_jnidemo_complex_Employee
#ifdef __cplusplus
extern "C" {
#endif
#undef com_fhr_jnidemo_complex_Employee_serialVersionUID
#define com_fhr_jnidemo_complex_Employee_serialVersionUID 3813074477864666655i64
/*
 * Class:     com_fhr_jnidemo_complex_Employee
 * Method:    raiseSalary
 * Signature: (D)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_com_fhr_jnidemo_complex_Employee_raiseSalary
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
